### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: The number of columns doesn't match.

### ISSUE THREAD

**Issue by dpuiu** [larryns/MitoScape#1]
Hello,

I have been trying to run MitoScape locally, using the instructions available on the github page.
I have first downloaded the MitoScape and gmap-gsnap latest versions, generated the gmap-gsnap indeces and aligned the reads.
MitoScape=1.0.jar fails with a  "number of columns doesn't match" error

#################################################################################

$ java -Xmx2G -jar ./MitoScape-1.0.jar --threads 1 --ld NUMTs_hg38.txt   --classifier MTClassifierModel.RF   --prefix chrM.A   --out outWARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/work-zfs/ssalzbe1/sw/packages/MitoScape/MitoScape-1.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2022-02-21 11:54:31 WARN  NativeCodeLoader:60 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Loading LD file: NUMTs_hg38.txt
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: The number of columns doesn't match.
Old column names (4): 1, 170256368, 170256655, 100
New column names (3): Variant1, Variant2, R
        at scala.Predef$.require(Predef.scala:281)
        at org.apache.spark.sql.Dataset.toDF(Dataset.scala:495)
        at MitoScape.LD.<init>(LD.scala:45)
        at MitoScape.MTClassify$.main(MTClassify.scala:149)
        at MitoScape.MTClassify.main(MTClassify.scala)

$ tree .
|-- MTClassifierModel.RF 
|-- MitoScape-1.0.jar
|-- NUMTs_hg38.txt 
|-- adam.log
|-- chrM.A_MT_MD.bam
`-- chrM.A_NT.bam

$ samtools view -H chrM.A_MT_MD.bam | head 
@HD     VN:1.0  SO:coordinate
@PG     ID:GSNAP        PN:gsnap        VN:2021-12-17   CL:~/sw/bin/gsnap.sse42 -D ~/Homo_sapiens/RefSeq/gsnap -d rCRS -A sam --nthreads=1 --sam-hardclip-use-S ../fastq/chrM.A_1.fq ../fastq/chrM.A_2.fq
@PG     ID:samtools     PN:samtools     PP:GSNAP        VN:1.14 CL:samtools sort
@PG     ID:samtools.1   PN:samtools     PP:samtools     VN:1.14 CL:samtools view -b
@PG     ID:samtools.2   PN:samtools     PP:samtools.1   VN:1.14 CL:samtools view -f 0x3 -b chrM.A_MT.bam
@PG     ID:samtools.3   PN:samtools     PP:samtools.2   VN:1.14 CL:samtools calmd -e -Q --output-fmt BAM /dev/stdin ~/Homo_sapiens/RefSeq/rCRS.fa
@PG     ID:samtools.4   PN:samtools     PP:samtools.3   VN:1.14 CL:samtools view -H chrM.A_MT_MD.bam
@SQ     SN:rCRS LN:16569        tp:circular

$ samtools view -H chrM.A_NT.bam | head 
@HD     VN:1.0  SO:coordinate
@PG     ID:GSNAP        PN:gsnap        VN:2021-12-17   CL:~/sw/bin/gsnap.sse42 -D ~/Homo_sapiens/RefSeq/gsnap/ -d hs38DH_no_chrM -A sam --nthreads=1 --sam-hardclip-use-S ../fastq/chrM.A_1.fq ../fastq/chrM.A_2.fq
@PG     ID:samtools     PN:samtools     PP:GSNAP        VN:1.14 CL:samtools sort
@PG     ID:samtools.1   PN:samtools     PP:samtools     VN:1.14 CL:samtools view -b
@PG     ID:samtools.2   PN:samtools     PP:samtools.1   VN:1.14 CL:samtools view -H chrM.A_NT.bam
@SQ     SN:chr1 LN:248956422
@SQ     SN:chr2 LN:242193529
@SQ     SN:chr3 LN:198295559
@SQ     SN:chr4 LN:190214555
@SQ     SN:chr5 LN:181538259

$ gsnap -v
GSNAP version 2021-12-17

**Comment by larryns** [comment]
Hi,

There's a mistake in the README instructions. The LD file is ```mitomap.ld```, **not** ```NUMTs_hg38.txt```. I've updated the README, but also have a look at the ```mitoscape.sh ```script in the ```scripts``` directory.

Sorry about that.

Best wishes,
Larry.

**Comment by dpuiu** [comment]
Thank you Larry.

I have managed to run MitoScape on my local machine using the following command:
java -Xmx2G -jar ./MitoScape-1.0.jar --threads 1  --prob 0.5  --ld mitomap.ld --numt NUMTs_hg38.txt --classifier MTClassifierModel.RF --prefix chrM.A --out chrM.A_MTDNA_0.5.bam

I have also run in it on Cavatica, using the same simulated reads.

I have compare the two BAM output files and noticed that for the local run, the read coverage drops to near zero in certain regions of the MitoScape output BAM file.

###############################################################################
# local run ; input  BAM, 5' coverage
$ bedtools genomecov -ibam chrM.A_MT_MD.bam -d | head -n 1
rCRS	1	1702

# local run ; input  BAM, median coverage
$ bedtools genomecov -ibam chrM.A_MT_MD.bam -d | sort -k3,3n | head -8284 | tail -1
rCRS	2142	2030

# local run ; output  BAM, 5' coverage
$ bedtools genomecov -ibam chrM.A_MTDNA_0.5.bam -d | head -n 1
rCRS	1	1

# local run ; output BAM, median cvg
$ bedtools genomecov -ibam chrM.A_MTDNA_0.5.bam -d | sort -k3,3n | head -8284 | tail -1
rCRS	14849	1949

###############################################################################
# Cavatica run ; input ; FASTQ reads
# Cavatica run ; output  BAM, 5' coverage
$ bedtools  genomecov -ibam  A_MTDNA.bam  -d | head -1
chrM	1	1642

# Cavatica run ; output BAM,  median coverage
$ bedtools  genomecov -ibam  A_MTDNA.bam  -d | sort -k3,3n | head -8284 | tail -1
chrM	15662	2030

###############################################################################

I was wondering if there still might be some problem with the local run

**Comment by larryns** [comment]
Yes, I'm not surprised. The local jar file does more aggressive filtering than the version in Cavatica. The recent jar file is the most up to date, bug free version. I didn't create new Docker images so the version in Cavatica is older. You should be able to achieve similar results if you adjust the probability in the jar version. What values you should use though, I can't really say. It really depends on how aggressive you want to filter potential NUMTs. The extreme case is setting the probability equal to 0.0 in which case no filtering will be done at all (not very useful).

Hope this helps.

Larry.

**Comment by dpuiu** [comment]
For  probabilities 0.01, 0.1, 0.5, the output bams were identical (they all contain low coverage regions) 
When I uses the 0.0 probability, the output bam was very similar to the input _MT_MD.bam file

**Comment by larryns** [comment]
I assume you're using the jar version; but yes what you're seeing isn't surprising. I expect the jar version to give different results from the Cavatica one, as there were several bug fixes and improvements both in my code and libraries used. The version that's tested in the paper is the jar version. 

Yes, probability 0.0 means no filtering is done, so the output should be the same as the input.

**Comment by larryns** [comment]
Closing due to lack of activity.
